Add article 'How to evolve an application - tests
talk-to-the-duck/talk-to-the-duck.github.io pull request #30
Opened 2022-11-01 19:54 UTC by emmanuelquinton

Add article 'How to evolve an application - tests  #16

2022-11-02 22:08 UTC, dcremonini requested changes
Please can you fix the requested changes?
Thank you.
Daniele

2022-11-02 22:08 UTC, dcremonini commented on content/posts/how-to-evolve-application-tests.md
> +![unit-test-gradle-file-location.png](images/posts/how-to-evolve-application/unit-test-gradle-file-location.png "image_tooltip")
Please add an empty line here otherwise the format of the output page is wrong.

2022-11-02 22:08 UTC, dcremonini commented on content/posts/comment-faire-evoluer-application-tests.fr.md
> +![integration-test-folder.png](/images/integration-test-folder.png "image_tooltip")
Can you please fix the image pathname?

2022-11-02 22:08 UTC, dcremonini commented on content/posts/comment-faire-evoluer-application-tests.fr.md
> +![unit-test-gradle-file-location.png](/images/unit-test-gradle-file-location.png "image_tooltip")
Can you please fix the image pathname?

2022-12-26 21:30 UTC, emmanuelquinton commented on content/posts/how-to-evolve-application-tests.md
> +Written by : Emmanuel Quinton
Done

2022-12-26 21:31 UTC, emmanuelquinton commented on content/posts/how-to-evolve-application-tests.md
> +Review by : Daniele Cremonini
Done

2023-01-09 20:54 UTC, merged