doc(t3d-53): Add French translation of 'how to evolve application cicd'
talk-to-the-duck/talk-to-the-duck.github.io pull request #55
Opened 2023-10-11 20:59 UTC by emmanuelquinton

2023-11-01 19:19 UTC, dcremonini requested changes

2023-11-01 19:19 UTC, dcremonini commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +* construire l'application
```suggestion
* construire l'application ;
```

2023-11-01 19:19 UTC, dcremonini commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +* vérifier que le code est formaté
```suggestion
* vérifier que le code est formaté ;
```

2023-11-01 19:19 UTC, dcremonini commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +  Exécuter les tests d'intégration * Exécuter les tests système
```suggestion
  * Exécuter les tests d'intégration ;
  * Exécuter les tests système.
```

2023-11-01 19:19 UTC, dcremonini commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +* construire le fichier jar
```suggestion
* construire le fichier jar ;
```

2023-11-01 19:19 UTC, dcremonini commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +Dans notre cas, nous avons sélectionné le workflow java avec gradle.
```suggestion
Dans notre cas, nous avons sélectionné le workflow Java avec gradle.
```

2023-11-01 19:19 UTC, dcremonini commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +* nous créons le job assemble qui est basé sur ubuntu-latest
```suggestion
* Nous créons le job assemble qui est basé sur ubuntu-latest
```

2023-11-01 19:19 UTC, dcremonini commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +* définir ce qu'est le CICD
```suggestion
* définir ce qu'est le CICD ;
```

2023-11-01 19:19 UTC, dcremonini commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +C'est pourquoi nous préférons utiliser GitLab, CircleCi ou GitHub Actions.
```suggestion
Nous préférons utiliser GitLab, CircleCi ou GitHub Actions car Jenkins nécessite un déploiement, une gestion et des ressources matérielles distincts.
```

2023-11-01 19:19 UTC, dcremonini commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +car Jenkins nécessite un déploiement, une gestion et des ressources matérielles distincts.
I'd delete this line.

2023-11-01 19:19 UTC, dcremonini commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +* pousser le rapport de l'IC Gitlab vers GitHub n'est pas possible.
```suggestion
* Pousser le rapport de la CI Gitlab vers GitHub n'est pas possible.
```

2023-11-01 19:19 UTC, dcremonini commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +* Comment ajouter les paramètres CICD à notre projet
```suggestion
* montrer comment ajouter les paramètres CICD à notre projet
```

2023-11-01 19:19 UTC, dcremonini commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +Nous voulons également que le pipeline soit exécuté à chaque commit sur la branche develop et les branches ci (avec le préfixe ci_).
```suggestion
Nous voulons également que le pipeline soit exécuté à chaque commit sur la branche _develop_ et les branches CI (avec le préfixe ci_).
```

2023-11-01 20:01 UTC, emmanuelquinton commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +Nous pourrions ajouter d'autres types de branches : feature(feat_), fix (fix_), documentation (doc_)
J'ai pas l'habitude d'utiliser feat/

2023-11-01 20:05 UTC, emmanuelquinton commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +* construire l'application
Plutôt un point

2023-11-01 20:07 UTC, emmanuelquinton commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +C'est pourquoi nous préférons utiliser GitLab, CircleCi ou GitHub Actions.
Done

2023-12-12 07:41 UTC, emmanuelquinton commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +Nous pourrions ajouter d'autres types de branches : feature(feat_), fix (fix_), documentation (doc_)
done

2023-12-12 07:41 UTC, emmanuelquinton commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +* construire l'application
done

2023-12-12 07:41 UTC, emmanuelquinton commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +* vérifier que le code est formaté
updated with dote

2023-12-12 07:43 UTC, emmanuelquinton commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +  Exécuter les tests d'intégration * Exécuter les tests système
Done with dote

2023-12-12 07:43 UTC, emmanuelquinton commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +* construire le fichier jar
Done

2023-12-12 07:43 UTC, emmanuelquinton commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +* pousser le rapport de l'IC Gitlab vers GitHub n'est pas possible.
Done

2023-12-12 07:44 UTC, emmanuelquinton commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +* Comment ajouter les paramètres CICD à notre projet
Done

2023-12-12 07:45 UTC, emmanuelquinton commented on content/posts/how-to-evolve-application-cicd/index.fr.md
> +Nous voulons également que le pipeline soit exécuté à chaque commit sur la branche develop et les branches ci (avec le préfixe ci_).
Done

2024-01-07 11:57 UTC, dcremonini commented
I pushed some fixes.
Can you have a look?

2024-07-19 21:04 UTC, dcremonini approved these changes

2024-07-19 21:07 UTC, merged